name: justwallpaper
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  conditional_builder_null_safety: ^0.0.6
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  dio: ^4.0.4
  cubit: ^0.1.2
  hexcolor: ^2.0.3
  #shared_preferences: ^2.0.11
  fluttertoast: ^8.0.8
  #flutter_cache_manager:
  #responsive_builder: ^0.4.1
  easy_splash_screen: ^1.0.3
  pull_to_refresh:
  flutter_share:
  path_provider: ^2.0.9
  gallery_saver:
  lazy_load_scrollview:
  tab_container: ^2.0.0
  cached_network_image:
  wallpaper_manager_flutter:
  flutter_cache_manager:


dev_dependencies:
  flutter_launcher_icons:

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_transparent.png"


  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: janna
      fonts:
        - asset: assets/fonts/janna.ttf
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf
